biocypher:
  dbms: postgresql
  offline: true
  strict_mode: true
  schema_config_path: config/full_schema_config.yaml
  output_directory: biocypher-out
neo4j:
  database_name: graph.db
  password: 'postgres'
  delimiter: '¦'
  quote_character: '"'

postgresql:
  database_name: postgres
  user: postgres
  password: postgres
  port: 5432
  quote_character: '"'
  delimiter: '\t'

  import_call_bin_prefix: ''
  import_call_file_prefix: biocypher-out/
